# Generated by Django 4.0.4 on 2022-04-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(to='snapvisite.category'),
        ),
    ]
