# Generated by Django 4.0.4 on 2022-05-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0004_alter_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='company_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='snapvisite.companyday'),
        ),
    ]
