# Generated by Django 4.0.4 on 2022-05-08 16:43

from django.db import migrations, models
import snapvisite.models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0007_alter_company_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=snapvisite.models.save_photo),
        ),
    ]
