# Generated by Django 4.0.4 on 2022-05-12 11:10

from django.db import migrations, models
import snapvisite.models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0010_alter_schedule_close_time_alter_schedule_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(default='static/snapvisite/images/default_company_photo.png', upload_to=snapvisite.models.save_photo),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=20),
        ),
    ]
