# Generated by Django 4.0.4 on 2022-05-12 11:32

from django.db import migrations, models
import snapvisite.models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0011_alter_company_photo_alter_schedule_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=snapvisite.models.save_photo),
        ),
    ]
