# Generated by Django 4.0.4 on 2022-05-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0014_alter_schedule_close_time_alter_schedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
