# Generated by Django 4.0.4 on 2022-05-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0015_alter_schedule_close_time_alter_schedule_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.IntegerField(default=30, help_text="Put time in minutes. Like '60' = 1h, '30' = 30min, '90' = 1h 30min"),
        ),
    ]
