# Generated by Django 4.0.4 on 2022-05-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0011_alter_schedule_close_time_alter_schedule_open_time'),
        ('snapvisite', '0016_alter_service_time'),
    ]

    operations = [
    ]
