# Generated by Django 4.0.4 on 2022-05-18 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snapvisite', '0018_alter_schedule_close_time_alter_schedule_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snapvisite.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snapvisite.timeslot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyday',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snapvisite.company'),
        ),
        migrations.AlterField(
            model_name='service',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapvisite.company'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='company_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapvisite.companyday'),
        ),
    ]
