# Generated by Django 4.0.4 on 2022-05-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0020_alter_appointment_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyday',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapvisite.company'),
        ),
    ]
