# Generated by Django 4.0.4 on 2022-05-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0021_alter_companyday_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='companyday',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
