# Generated by Django 4.0.4 on 2022-05-19 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0022_remove_timeslot_end_time_alter_companyday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyday',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapvisite.company', unique_for_date=models.DateField()),
        ),
        migrations.AlterField(
            model_name='companyday',
            name='date',
            field=models.DateField(),
        ),
    ]
