# Generated by Django 4.0.4 on 2022-05-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0024_alter_companyday_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyday',
            options={'ordering': ('date',), 'verbose_name': 'companyday', 'verbose_name_plural': 'companydays'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ('start_time',), 'verbose_name': 'timeslot', 'verbose_name_plural': 'timeslots'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
