# Generated by Django 4.0.4 on 2022-05-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0026_appointment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snapvisite.timeslot'),
        ),
    ]
