# Generated by Django 4.0.4 on 2022-05-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0027_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(default='123', max_length=10),
        ),
    ]
