# Generated by Django 4.0.4 on 2022-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0028_appointment_appointment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.BooleanField(choices=[(True, 'Pay with card now'), (False, 'Pay by cash on visit')], default=False),
        ),
    ]
