# Generated by Django 4.0.4 on 2022-05-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0029_alter_appointment_appointment_code_and_more'),
        ('snapvisite', '0029_alter_companyday_options_company_email_and_more'),
    ]

    operations = [
    ]
