# Generated by Django 4.0.4 on 2022-05-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0030_merge_20220522_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyday',
            options={'ordering': ('date',), 'verbose_name': 'companyday', 'verbose_name_plural': 'companydays'},
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.IntegerField(default=30, help_text="Put time in minutes. Like '60' = 1h, '30' = 30min, '90' = 1h 30min"),
        ),
    ]
