# Generated by Django 4.0.4 on 2022-05-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0031_alter_companyday_options_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='close_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='open_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
