# Generated by Django 4.0.4 on 2022-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapvisite', '0032_alter_address_postal_code_alter_schedule_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=35),
        ),
    ]
